### ISSUE TITLE
htop 3.1.1 segfaults when adding "CPU average" meter

### ISSUE THREAD

**Issue by scalisi** [htop-dev/htop#844]
1. I installed htop 3.1.1 from source on Debian Buster.
2. I ran htop and noticed that my custom header had reverted to the default.
3. I deleted my htoprc.
4. I reconfigured htop, which included adding the **CPU average** meter to the header.
5. I quit htop.
6. "Segmentation fault" was printed in my terminal.
7. I ran htop again and saw that my custom header had reverted to the default again.
8. After some trial and error, it seemed that the segfault occurred only when the **CPU average** meter was added to the header.
9. I deleted my htoprc again and the only change I made was adding the **CPU average** meter to the header.
10. I quit htop.
11. "Segmentation fault" was printed in my terminal.

I didn't experience this issue with htop 3.1.0, which I also installed from source on Debian Buster.

**Comment by fasterit** [comment]
Could you please compile with `--enable-debug`¸ and then provide a `gdb` stack backtrace of the segfault?

`gdb -batch -ex "run" -ex "bt full" ./htop 2>&1` should do.

NB: DLange could not reproduce locally.

**Comment by scalisi** [comment]
```
Program received signal SIGSEGV, Segmentation fault.
__GI___libc_free (mem=0x31) at malloc.c:3093
3093    malloc.c: No such file or directory.
#0  __GI___libc_free (mem=0x31) at malloc.c:3093
        ar_ptr = <optimized out>
        p = <optimized out>
        hook = 0x0
#1  0x000055555557d555 in String_freeArray (s=0x5555555a5c80) at XUtils.c:158
        i = <optimized out>
#2  0x000055555557a49f in Settings_delete (this=this@entry=0x5555555a58d0) at Settings.c:31
        i = 0
#3  0x0000555555567bcc in CommandLine_run (name=<optimized out>, argc=<optimized out>, argv=<optimized out>) at CommandLine.c:395
        lc_ctype = <optimized out>
        flags = {pidMatchList = 0x0, commFilter = <optimized out>, userId = <optimized out>, sortKey = <optimized out>, delay = -1, useColors = true, enableMouse = <optimized out>, treeView = <optimized out>, allowUnicode = true, highlightChanges = <optimized out>, highlightDelaySecs = <optimized out>, readonly = <optimized out>}
        ut = 0x5555555a0930
        dc = 0x5555555a0ac0
        dm = 0x0
        pl = 0x5555555a0c30
        settings = 0x5555555a58d0
        header = 0x5555555a5d70
        panel = <optimized out>
        state = {settings = 0x5555555a58d0, ut = 0x5555555a0930, pl = 0x5555555a0c30, mainPanel = 0x5555556c2d10, header = 0x5555555a5d70, pauseProcessUpdate = false, hideProcessSelection = false}
        scr = 0x5555556c6b60
#4  0x00007ffff7c2909b in __libc_start_main (main=0x555555563a70 <main>, argc=1, argv=0x7fffffffdeb8, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffdea8) at ../csu/libc-start.c:308
        self = <optimized out>
        result = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {0, -3130608271126653967, 93824992295568, 140737488346800, 0, 0, -9090360737828137999, -9090342774506613775}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x7fffffffdec8, 0x7ffff7ffe190}, data = {prev = 0x0, cleanup = 0x0, canceltype = -8504}}}
        not_first_call = <optimized out>
#5  0x0000555555563aba in _start ()
No symbol table info available.
```
